services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
