runtime: nodejs16

# Environment variables (non-sensitive)
env_variables:
  PORT: "8080"
  PROJECT_ID: "bpr-unified-platform"
  NODE_ENV: "production"

# Entrypoint
entrypoint: node server.js

# Secure all routes
handlers:
  - url: /.*
    script: auto
    secure: always
